# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 846ec5e38305f438f153b96816736a46473987b451c08a99c381f1229d64a2ed967e202d9c07e4d1cbb023b71b7ac5decd1165dfe05d6ce0ffdfcd94d787b235

test:
  secret_key_base: 018770e27966421f59068c607a80f9e9f6a5e1f1b71959fe926e9350df538feebe8155f3902373a1a484cdee32b6053274c427d71753a581fb90b7d18e71c9a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
